// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/http"

	"github.com/go-faster/errors"

	ht "github.com/ogen-go/ogen/http"
)

func encodeSetRequest(
	req *SetReqWithContentType,
	r *http.Request,
) error {
	contentType := req.ContentType
	if contentType != "" && !ht.MatchContentType("*/*", contentType) {
		return errors.Errorf("%q does not match mask %q", contentType, "*/*")
	}
	{
		req := req.Content
		body := req
		ht.SetBody(r, body, contentType)
		return nil
	}
}
