// Code generated by ogen, DO NOT EDIT.

package client

import (
	"bytes"
	"io"
	"mime"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

func decodeDeleteResponse(resp *http.Response) (res *DeleteNoContent, _ error) {
	switch resp.StatusCode {
	case 204:
		// Code 204.
		return &DeleteNoContent{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeDeleteNamespaceResponse(resp *http.Response) (res *DeleteNamespaceNoContent, _ error) {
	switch resp.StatusCode {
	case 204:
		// Code 204.
		return &DeleteNamespaceNoContent{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeGetResponse(resp *http.Response) (res GetRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ht.MatchContentType("*/*", ct):
			reader := resp.Body
			b, err := io.ReadAll(reader)
			if err != nil {
				return res, err
			}

			response := GetOK{Data: bytes.NewReader(b)}
			var wrapper GetOKHeaders
			wrapper.Response = response
			h := uri.NewHeaderDecoder(resp.Header)
			// Parse "X-Content-Type" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "X-Content-Type",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							val, err := d.DecodeValue()
							if err != nil {
								return err
							}

							c, err := conv.ToString(val)
							if err != nil {
								return err
							}

							wrapper.XContentType = c
							return nil
						}); err != nil {
							return err
						}
					} else {
						return validate.ErrFieldRequired
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse X-Content-Type header")
				}
			}
			// Parse "X-Ttl" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "X-Ttl",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotXTTLVal float64
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToFloat64(val)
								if err != nil {
									return err
								}

								wrapperDotXTTLVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.XTTL.SetTo(wrapperDotXTTLVal)
							return nil
						}); err != nil {
							return err
						}
						if err := func() error {
							if wrapper.XTTL.Set {
								if err := func() error {
									if err := (validate.Float{}).Validate(float64(wrapper.XTTL.Value)); err != nil {
										return errors.Wrap(err, "float")
									}
									return nil
								}(); err != nil {
									return err
								}
							}
							return nil
						}(); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse X-Ttl header")
				}
			}
			return &wrapper, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 404:
		// Code 404.
		return &GetNotFound{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeKeysResponse(resp *http.Response) (res *Batch, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response Batch
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeSetResponse(resp *http.Response) (res *SetNoContent, _ error) {
	switch resp.StatusCode {
	case 204:
		// Code 204.
		return &SetNoContent{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}
