// Code generated by ogen, DO NOT EDIT.

package client

// DeleteParams is parameters of delete operation.
type DeleteParams struct {
	// Key-Value namespace.
	Namespace string
	// Key name.
	Key string
}

// DeleteNamespaceParams is parameters of deleteNamespace operation.
type DeleteNamespaceParams struct {
	// Key-Value namespace.
	Namespace string
}

// GetParams is parameters of get operation.
type GetParams struct {
	// Key-Value namespace.
	Namespace string
	// Key name.
	Key string
}

// KeysParams is parameters of keys operation.
type KeysParams struct {
	// Key-Value namespace.
	Namespace string
	// Cursor of the previous page, should be passed in from the previous request or absent for new
	// request.
	Cursor OptInt64
}

// SetParams is parameters of set operation.
type SetParams struct {
	// Key-Value namespace.
	Namespace string
	// Key name.
	Key string
	// Time-to-live for the key in seconds (floating).
	TTL OptFloat64
}
