// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dbo

import (
	"database/sql"
)

type Value struct {
	ID          int64
	ExpireAt    sql.NullInt64
	ContentType string
	Namespace   string
	Key         string
	Value       []byte
}

type ValueKey struct {
	ID        int64
	Key       string
	Namespace string
	ExpireAt  sql.NullInt64
}
