// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Delete implements delete operation.
//
// Delete key. Does nothing if key not exists.
//
// DELETE /{namespace}/{key}
func (UnimplementedHandler) Delete(ctx context.Context, params DeleteParams) error {
	return ht.ErrNotImplemented
}

// DeleteNamespace implements deleteNamespace operation.
//
// Delete namespace and all keys.
//
// DELETE /{namespace}
func (UnimplementedHandler) DeleteNamespace(ctx context.Context, params DeleteNamespaceParams) error {
	return ht.ErrNotImplemented
}

// Get implements get operation.
//
// Get value by key.
//
// GET /{namespace}/{key}
func (UnimplementedHandler) Get(ctx context.Context, params GetParams) (r GetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Keys implements keys operation.
//
// List keys in namespace page by page. Iteration may not be consistent if there are updates between
// pages.
// At the end of page, operation will return empty list.
// Iteration order is non-deterministic, but generally tends to be from oldest key to newest key.
//
// GET /{namespace}
func (UnimplementedHandler) Keys(ctx context.Context, params KeysParams) (r *Batch, _ error) {
	return r, ht.ErrNotImplemented
}

// Set implements set operation.
//
// Create or replace value in namespace.
//
// POST /{namespace}/{key}
func (UnimplementedHandler) Set(ctx context.Context, req *SetReqWithContentType, params SetParams) error {
	return ht.ErrNotImplemented
}
